import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./css/breakpoints_prefixed.css";
import "./css/slick.css";
import "./css/styles_prefixed.css";
import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <Script src="./public/js/TweenMax.min.js"/> 
 <Script src="./public/js/ScrollToPlugin.min.js"/> 


 <Script src="/public/js/jquery.min.js"/> 
 <Script src="/public/js/modernizr-custom.js"/> 
 <Script src="/public/js/jquery.inview.min.js"/> 
 <Script src="/public/js/social-icons.js"/>
 <Script src="/public/js/smartresize.js"/> 
 <Script src="/public/js/slick.min.js"/> 
 <Script src="../public/js/imagesloaded.js"/> 
 <Script src="/public/js/isotope.pkgd.min.js"/> 
 <Script src="/public/js/player.js"/> 
 <Script src="/public/js/site.js"/> 
 <Script src="https://unpkg.com/imagesloaded@5/imagesloaded.pkgd.min.js"/>


      </body>
    </html>
  );
}
